#!/bin/sh
set -e
. $DESRES_ROOT/modules/init/sourceme.sh
module add gardenutils/1.9.2/lib-sh
. desres-install-functions
trap 'desres_trapped_exit' EXIT

desres_require_cleanenv

NAME=msys
PKG_VERSION=0.7.0

VERSION=${PKG_VERSION}
DESCRIPTION="Biomolecular Structure Library"

GCC=gcc/4.5.1-22A
SCONS=scons/2.0.1-04A
SCONSUTILS=sconsutils/1.22
BOOST=boost/1_45_0-21A
PYTHON=Python/2.7.1-06A
SQLITE=sqlite/3.6.22-01
PCRE=pcre/7.4-01
ANTLR=antlr/3.1.3-06
JSON=fastjson/1.4.0
SPHINX=Sphinx/1.1-01A

loadmodules() {
    module load \
        $GCC/bin \
        $PYTHON/bin \
        $PYTHON/lib \
        $SCONS/bin \
        $SCONSUTILS/lib-python \
        $BOOST/Release/lib \
        $SQLITE/lib \
        $PCRE/lib-shared \
        $ANTLR/lib \
        $JSON/lib \
        $SPHINX/bin 
    

   desres_module_stripcolons
}

genmodules() {
    # get modulefile boilerplate
    hdr=`desres_module_header $NAME $VERSION`

    # Python modules
    cat << EOF > $MODULEDIR/lib-python
$hdr
module-whatis {$NAME - $DESCRIPTION}

prereq $PYTHON/bin
prepend-path PYTHONPATH $PREFIX/lib/python
EOF

    # library
    cat << EOF > $MODULEDIR/lib
$hdr
module-whatis {$NAME - $DESCRIPTION}

prepend-path DESRES_MODULE_CPPFLAGS -I$PREFIX/include
prepend-path DESRES_MODULE_LDFLAGS "-L$PREFIX/lib -Wl,-rpath,$PREFIX/lib"
setenv MSYS_PREFIX "$PREFIX"
EOF

    # executables
    cat << EOF > $MODULEDIR/bin
$hdr
module-whatis {$NAME - $DESCRIPTION}
prepend-path PATH $PREFIX/bin
prepend-path MANPATH $PREFIX/doc/man
setenv MSYS_PREFIX "$PREFIX"
setenv MSYS_CLEANENV "-eMSYS_PREFIX -m $PYTHON/bin -m $NAME/$VERSION/lib-python"
EOF
}

genhelp() {
    cat <<EOF >> $PREFIX/ModulesHelp

See documentation in 
$PREFIX/doc/html/index.html

This is a pre-release version of msys.

0.7.0  Many new tools.
0.6.2  Documentation

EOF
}

gendocs() {
    (cd doc && make man html)
    mkdir -p $PREFIX/doc/man/man1
    cp -r doc/build/html $PREFIX/doc/
    cp doc/build/man/*.1 $PREFIX/doc/man/man1
}

case $1 in
    --name)
        echo $NAME
        ;;
    --version)
	echo $VERSION
        ;;
    --exec)
        shift
	loadmodules
        "$@"
        ;;
    --install)
	loadmodules
	desres_require_prefix
	desres_require_moduledir

        $0 --exec scons -j4 install PREFIX=${PREFIX} OBJDIR=${TMPDIR}

	genhelp
	genmodules
        gendocs

        ;;
    --help)
        desres_install_helper_usage
        ;;
    # It's not an error if nothing matches.  desres-install may invent
    # other arguments in the future.
esac

desres_clean_exit 0
