#!/bin/sh
eval "$(/usr/bin/garden-exec)"

NAME=msys
VERSION=`src/version.py`
DESCRIPTION="Biomolecular Structure Library"

# module versions that scripts in ./tools need to know
. ./MODULES

# shared library dependencies
GCC=gcc/4.9.2-30B
BOOST=boost/1.59.0-03
LPSOLVE=lp_solve/5.5.2.0-05A
INCHI=inchi/1.04-05
SNAPPY=snappy/1.1.2-01
TEXLIVE=texlive/20120701-03
THREEROE=ThreeRoe/0.04
SQLITE=sqlite/3.10.2-06A

# build and documentation
SCONS=scons/2.3.4-10A
SCONSUTILS=sconsutils/1.40

loadmodules() {
    garden add \
        $GCC/bin \
        $PYTHON/bin \
        $PYTHON/lib \
        $SCONS/bin \
        $SCONSUTILS/lib-python \
        $BOOST/lib \
        $LPSOLVE/lib \
        $SNAPPY/lib \
        $INCHI/lib \
        $SQLITE/lib \
	$THREEROE/lib \
	$TEXLIVE/bin
    
   export MSYS_VERSION=$VERSION
}

genmodules() {
    mkdir -p $GARDENDIR
    cat << EOF > $GARDENDIR/lib-python
prereq $PYTHON/bin
prepend-path PYTHONPATH $PREFIX/lib/python
setenv MSYS_PREFIX "$PREFIX"
EOF

    # library
    cat << EOF > $GARDENDIR/lib
prepend-path DESRES_MODULE_CPPFLAGS -I$PREFIX/include
prepend-path DESRES_MODULE_LDFLAGS  -L$PREFIX/lib -Wl,-rpath,$PREFIX/lib
setenv MSYS_PREFIX "$PREFIX"
EOF

    # executables
    cat << EOF > $GARDENDIR/bin
prepend-path PATH $PREFIX/bin
prepend-path MANPATH $PREFIX/doc/man
setenv MSYS_PREFIX "$PREFIX"
EOF
}

genhelp() {
    cat release_notes.txt >> $PREFIX/ModulesHelp
    cat <<EOF >> $PREFIX/ModulesHelp

See documentation in 
http://gardendoc.nyc.desres.deshaw.com/$NAME/$VERSION/doc/html/index.html

EOF

}

gendocs() {
    (cd doc && VERSION=$VERSION BINDIR=${PREFIX}/bin make genhelp man html latexpdf)
    mkdir -p $PREFIX/doc/man/man1
    cp -r doc/build/html $PREFIX/doc/
    cp doc/build/latex/Msys.pdf $PREFIX/doc/
    cp doc/build/man/*.1 $PREFIX/doc/man/man1
}

case $1 in
    --name)
        echo $NAME
        ;;
    --version)
	echo $VERSION
        ;;
    --exec)
        shift
	loadmodules
        "$@"
        ;;
    --install)
	loadmodules

        $0 --exec scons install -j 12 PREFIX=${PREFIX} OBJDIR=${TMPDIR}

        ./tests/ut.py

	genhelp
	genmodules
        gendocs

        ;;
    --help)
        desres_install_helper_usage
        ;;
    # It's not an error if nothing matches.  desres-install may invent
    # other arguments in the future.
esac

exit 0
