#!/bin/sh
set -e
#set -x
. $DESRES_ROOT/modules/init/sourceme.sh
module add gardenutils/1.9.2/lib-sh
. desres-install-functions
trap 'desres_trapped_exit' EXIT

desres_require_cleanenv

NAME=msys
VERSION=`src/version.py`
DESCRIPTION="Biomolecular Structure Library"

# shared library dependencies
GCC=gcc/4.7.2-23A
BOOST=boost/1_51_0-28A
PYTHON=Python/2.7.3-07A
SQLITE=sqlite/3.6.23.1-02A
JSON=fastjson/1.5.1
MOLFILE=molfile/1.11.7
PERIODICFIX=periodicfix/2.4.9
NUMPY=numpy/1.6.2-32A
LPSOLVE=lp_solve/5.5.2.0-03A
PRIMEGEN=primegen/0.97-05
ZLIB=zlib/1.2.4-10A
INCHI=inchi/1.04-05
EIGEN=eigen/3.1.2-01        # for tools/atommatch
TEXLIVE=texlive/20120701-03

# build and documentation
SCONS=scons/2.3.0-10A
SCONSUTILS=sconsutils/1.37
SPHINX=Sphinx/1.1.3-04A

loadmodules() {
    module load \
        $GCC/bin \
        $PYTHON/bin \
        $PYTHON/lib \
        $NUMPY/include \
        $NUMPY/lib-python \
        $SCONS/bin \
        $SCONSUTILS/lib-python \
        $BOOST/Release/lib \
        $SQLITE/lib \
        $JSON/lib \
        $PERIODICFIX/lib \
        $PERIODICFIX/lib-python \
        $MOLFILE/lib \
        $LPSOLVE/lib \
        $PRIMEGEN/lib \
        $ZLIB/lib \
        $INCHI/lib \
        $EIGEN/lib \
        $SPHINX/bin \
	$TEXLIVE/bin
    
   export MSYS_VERSION=$VERSION

   desres_module_stripcolons
}

genmodules() {
    # get modulefile boilerplate
    hdr=`desres_module_header $NAME $VERSION`

    # Python modules
    cat << EOF > $MODULEDIR/lib-python
$hdr
module-whatis {$NAME - $DESCRIPTION}

prereq $PYTHON/bin
prereq $NUMPY/lib-python
prepend-path PYTHONPATH $PREFIX/lib/python
setenv MSYS_PREFIX "$PREFIX"
EOF

    # library
    cat << EOF > $MODULEDIR/lib
$hdr
module-whatis {$NAME - $DESCRIPTION}

prepend-path DESRES_MODULE_CPPFLAGS -I$PREFIX/include
prepend-path DESRES_MODULE_LDFLAGS "-L$PREFIX/lib -Wl,-rpath,$PREFIX/lib"
prepend-path DESRES_MODULE_LDLIBS   -lmsys
setenv MSYS_PREFIX "$PREFIX"
EOF

    # executables
    cat << EOF > $MODULEDIR/bin
$hdr
module-whatis {$NAME - $DESCRIPTION}
prepend-path PATH $PREFIX/bin
prepend-path MANPATH $PREFIX/doc/man
setenv MSYS_PREFIX "$PREFIX"
EOF
}

genhelp() {
    cat release_notes.txt >> $PREFIX/ModulesHelp
    cat <<EOF >> $PREFIX/ModulesHelp

See documentation in 
http://gardendoc.nyc.desres.deshaw.com/$NAME/$VERSION/doc/html/index.html

EOF
}

gendocs() {
    (cd doc && VERSION=$VERSION BINDIR=${TMPDIR}/bin make genhelp man html latexpdf)
    mkdir -p $PREFIX/doc/man/man1
    cp -r doc/build/html $PREFIX/doc/
    cp doc/build/latex/Msys.pdf $PREFIX/doc/
    cp doc/build/man/*.1 $PREFIX/doc/man/man1
}

case $1 in
    --name)
        echo $NAME
        ;;
    --version)
	echo $VERSION
        ;;
    --exec)
        shift
	loadmodules
        "$@"
        ;;
    --install)
	loadmodules
	desres_require_prefix
	desres_require_moduledir

        $0 --exec scons install -j4 PREFIX=${PREFIX} OBJDIR=${TMPDIR}

        ./tests/ut.py

	genhelp
	genmodules
        gendocs

        ;;
    --help)
        desres_install_helper_usage
        ;;
    # It's not an error if nothing matches.  desres-install may invent
    # other arguments in the future.
esac

desres_clean_exit 0
