#!/bin/sh
eval "$(garden-exec)"

NAME=msys
VERSION=1.7.202
DESCRIPTION="Biomolecular Structure Library"

# module versions that scripts in ./tools need to know
. ./MODULES

# shared library dependencies
BOOST=boost/1.59.0-13
LPSOLVE=lp_solve/5.5.2.0-05A
INCHI=inchi/1.04-05
SQLITE=sqlite/3.10.2-06A
SCONSUTILS=sconsutils/1.40
FLEX=flex/2.5.35-2
BISON=bison/2.4.1-11A

loadmodules() {
    garden load \
        $PYTHON/lib \
        $SCONSUTILS/lib-python \
        $BOOST/lib \
        $LPSOLVE/lib \
        $INCHI/lib \
        $FLEX/bin \
        $BISON/bin \
        $SQLITE/lib \

    export MSYS_VERSION=$VERSION
}

genmodules() {
    mkdir -p $GARDENDIR
    cat << EOF > $GARDENDIR/lib-python
prereq $PYTHON/bin
prepend-path PYTHONPATH $PREFIX/lib/python
setenv MSYS_PREFIX "$PREFIX"
EOF

    # library
    cat << EOF > $GARDENDIR/lib
prepend-path DESRES_MODULE_CPPFLAGS -I$PREFIX/include
prepend-path DESRES_MODULE_LDFLAGS  -L$PREFIX/lib:-Wl,-rpath,$PREFIX/lib
prereq $PYTHON/lib
prereq $BOOST/lib
prereq $SQLITE/lib
setenv MSYS_PREFIX $PREFIX
EOF

    # executables
    cat << EOF > $GARDENDIR/bin
prepend-path PATH $PREFIX/bin
setenv MSYS_PREFIX $PREFIX
EOF
}

genhelp() {
    cat release_notes.txt >> $PREFIX/ModulesHelp
    cat <<EOF >> $PREFIX/ModulesHelp

See documentation in 
http://gardendoc.nyc.desres.deshaw.com/$PREFIX/doc/html/index.html

EOF

}

gendocs() {
    (cd doc && VERSION=$VERSION BINDIR=$PREFIX/bin make clean genhelp html )
    cp -r doc/build/html $PREFIX/doc/
}

case $1 in
    --name)
        echo $NAME
        ;;
    --version)
	echo $VERSION
        ;;
    --exec)
        shift
	loadmodules
        "$@"
        ;;
    --install)
	loadmodules

        $0 --exec scons install -j 12 PREFIX=$PREFIX OBJDIR=$TMPDIR

        ./tests/ut.py
        ./tests/molfile_ut.py

	genhelp
	genmodules
        gendocs

        ;;
    --help)
        desres_install_helper_usage
        ;;
    # It's not an error if nothing matches.  garden-install may invent
    # other arguments in the future.
esac

exit 0
