#!/bin/sh
eval "$(garden-exec)"
set -e

NAME=msys
VERSION=1.7.210c7
DESCRIPTION="Biomolecular Structure Library"

# module versions that scripts in ./tools need to know
. ./MODULES

# shared library dependencies
GCC=gcc/6.3.0-01c7
BOOST=boost/1.63.0-01c7
LPSOLVE=lp-solve/5.5.2.0-01c7
INCHI=inchi/1.04-01c7
SQLITE=sqlite/3.16.2-02c7
SCONSUTILS=sconsutils/1.40-01c7
THREEROE=threeroe/0.10.1c7
RTD=sphinx-rtd-theme/0.2.4-01c7
PYTHON3=desres-python/3.6.1-01c7
BOOST_PYTHON3=boost-python36/1.63.0-01c7

loadmodules() {
    # desres-python/3.6.1/bin sets PYTHONPATH!  That was a mistake.
    garden load $PYTHON3/bin
    unset PYTHONPATH

    garden load \
        $GCC/bin \
        $PYTHON/bin \
        $BOOST/lib \
        $BOOST_PYTHON3/lib \
        $LPSOLVE/lib \
        $INCHI/lib \
        $SQLITE/lib-static \
        $THREEROE/lib \
        $SCONSUTILS/lib-python \
        $RTD/lib-python \

    export MSYS_VERSION=$VERSION
}

genmodules() {
    cat << EOF > $GARDENDIR/lib-python
prereq $PYTHON/bin
prepend-path PYTHONPATH $PREFIX/lib/python
EOF
    cat << EOF > $GARDENDIR/lib-python3
prereq $PYTHON3/bin
prepend-path PYTHONPATH $PREFIX/lib/python3
EOF

    # library
    cat << EOF > $GARDENDIR/lib
prepend-path DESRES_MODULE_CPPFLAGS -I$PREFIX/include
prepend-path DESRES_MODULE_LDFLAGS  -L$PREFIX/lib:-Wl,-rpath,$PREFIX/lib
prereq $BOOST/lib
EOF

    # executables
    cat << EOF > $GARDENDIR/bin
prepend-path PATH $PREFIX/bin
EOF
}

genhelp() {
    cat <<EOF
See documentation in
http://gardendoc.nyc.desres.deshaw.com/$PREFIX/doc/html/index.html

Release notes:

EOF
cat doc/source/release_notes.txt
}

gendocs() {
    (cd doc && VERSION=$VERSION BINDIR=$PREFIX/bin make clean genhelp html )
    cp -r doc/build/html $PREFIX/doc/
}

case $1 in
    --name)
        echo $NAME
        ;;
    --version)
	echo $VERSION
        ;;
    --exec)
        shift
	loadmodules
        "$@"
        ;;
    --garden-help)
        genhelp
        ;;
    --install)
	loadmodules

        nprocs=`getconf _NPROCESSORS_ONLN`
        $0 --exec scons install -j $nprocs PREFIX=$PREFIX OBJDIR=$TMPDIR
        python3 -m compileall $PREFIX/lib/python3

        ./tests/ut.py
        ./tests/ut.py -3
        ./tests/molfile_ut.py

	genhelp
	genmodules
        gendocs

        ;;
    --help)
        desres_install_helper_usage
        ;;
    # It's not an error if nothing matches.  garden-install may invent
    # other arguments in the future.
esac

exit 0
