#!/bin/sh
eval "$(garden-exec)"
set -e

NAME=msys

# module versions that scripts in ./tools need to know
. ./env.sh

# shared library dependencies
SCONS=scons/2.5.1-03c7
GCC=gcc/6.3.0-01c7
BOOST=boost/1.67.0-01c7
LPSOLVE=lp-solve/5.5.2.0-01c7
INCHI=inchi/1.05-01c7
SQLITE=sqlite/3.22.0-02c7
BOOST_PYTHON3=boost-python36/1.67.0-01c7
SCONSUTILS=sconsutils/1.46c7

loadmodules() {
    # load $PYTHON last so that we use python2 for sphinx, since
    # our conf.py points to the python2 install dir.
    garden load \
        $GCC/bin \
        $PYTHON3/bin \
        $PYTHON/bin \
        $SCONS/bin \
        $BOOST/lib \
        $BOOST_PYTHON3/lib \
        $LPSOLVE/lib \
        $INCHI/lib \
        $SQLITE/lib-static \
        $SCONSUTILS/lib-python \

    export PYTHONVER=27,36
    export MSYS_WITH_LPSOLVE=1
    export MSYS_WITH_INCHI=1
}

genmodules() {
    cat << EOF > $GARDENDIR/lib-python
load $PYTHON/bin
prepend-path PYTHONPATH $PREFIX/lib/python
EOF
    cat << EOF > $GARDENDIR/lib-python3
load $PYTHON3/bin
prepend-path PYTHONPATH $PREFIX/lib/python
EOF

    # library
    cat << EOF > $GARDENDIR/lib
prepend-path DESRES_MODULE_CPPFLAGS -I$PREFIX/include
prepend-path DESRES_MODULE_LDFLAGS  -L$PREFIX/lib:-Wl,-rpath,$PREFIX/lib
prereq $BOOST/lib
EOF

    # executables
    cat << EOF > $GARDENDIR/bin
prepend-path PATH $PREFIX/bin
EOF
}

genhelp() {
    cat <<EOF
Molecular structure and forcefield tools.

Release notes:

EOF
cat doc/source/release_notes.txt
}

gendocs() {
    (cd doc && BINDIR=$PREFIX/bin make clean genhelp html )
    cp -r doc/build/html $PREFIX/doc/
}

case $1 in
    --name)
        echo $NAME
        ;;
    --version)
	echo `src/version.py`c7
        ;;
    --exec)
        shift
	loadmodules
        "$@"
        ;;
    --garden-help)
        genhelp
        ;;
    --install)
	loadmodules

        nprocs=`getconf _NPROCESSORS_ONLN`
        $0 --exec scons install -j $nprocs PREFIX=$PREFIX OBJDIR=$TMPDIR

        ./tests/ut.py
        ./tests/ut.py -3
        ./tests/molfile_ut.py

        ./tests/oechem_ut.py
        ./tests/oechem_ut.py -3

        ./tests/rdkit_ut.py
        ./tests/rdkit_ut.py -3

	genhelp
	genmodules
        gendocs

        ;;
esac

exit 0
