Import('msysenv')
Import('libmsys')

env=msysenv.Clone()
env.Prepend(LIBS=[libmsys, 'msys-core', 'pthread'])
env.Append(CPPPATH='../src')

for p in Glob('test_*.cxx'):
    env.AddExampleProgram(p.name[:-4],p.name)

env=msysenv.Clone()
env.Prepend(LIBS=['msys-core'])
env.Append(CPPPATH='../src')

for p in Glob('core_test_*.cxx'):
    env.AddExampleProgram(p.name[:-4],p.name)
