Import('env')
Import('libmsys')

env=env.Clone()
env.Prepend(CPPPATH=['../src'], LIBS=[libmsys])

env.AddUnitTest('test_params', 'test_params.cxx')
env.AddUnitTest('test_dms', 'test_dms.cxx')
env.AddUnitTest('test_atomsel', 'test_atomsel.cxx')
env.AddUnitTest('test_schema', 'test_schema.cxx')
env.AddUnitTest('test_mae', 'test_mae.cxx')
env.AddUnitTest('test_value', 'test_value.cxx')
env.AddUnitTest('test_json', 'json.cxx')
env.AddUnitTest('test_amber', 'amber.cxx')

