Import('env')
Import('libmsys')

env=env.Clone()
env.Append( 
        CPPPATH=['../src'],
        LIBS=['msys', 'boost_python$BOOST_SUFFIX'] )

pymodfiles='''
analyze.cxx
annotated_system.cxx
atom.cxx
bond.cxx
residue.cxx
chain.cxx
override.cxx
param.cxx
system.cxx
term.cxx
vector.cxx
io.cxx
graph.cxx
inchi.cxx
pymod.cxx
wrap_obj.cxx
'''.split()

pyext=env.AddPythonExtension('_msys', pymodfiles, prefix='msys')
env.Requires(pyext, libmsys)
env.AddPythonModule('__init__.py', prefix='msys')
env.AddPythonModule('atomsel.py', prefix='msys')

