Import('msysenv')
env=msysenv.Clone()
env.Append( 
        CPPPATH=['../../src', '../'],
        CCFLAGS='-Wno-unused-function'.split(),
        LIBS=['msys', 'boost_python$MSYS_BOOST_SUFFIX', 'boost_thread$MSYS_BOOST_SUFFIX'])

if env['PLATFORM']=='darwin':
    env.Append(CCFLAGS='-Wno-error')
else:
    env.Append(CCFLAGS='-Wno-cpp')

env.Append(CPPPATH='..')
ext=env.AddPythonExtension('_molfile', env.Split('''
plugin.cxx
reader.cxx
atom.cxx
frame.cxx
writer.cxx
dtrreader.cxx
molfilemodule.cxx
'''), prefix='msys/molfile')

env.AddPythonExtension('findframe','findframemodule.cxx',
        prefix='msys/molfile')

env.AddPythonModule('__init__.py',prefix='msys/molfile')

