#!/bin/sh

: ${DMSDIFF:=diff}

[ -z "$1" -o -z "$2" ] && {
    echo "Usage: $0 <dms1> <dms2>" 1>&2
    exit 1
}

set -e
set -x

d1=$1; shift
d2=$1; shift

opts="--without-provenance --without-forcefield --without-paraminfo $@" 

out1=/tmp/dms-dump.$$.1
out2=/tmp/dms-dump.$$.2

trap '/bin/rm -f "$out1" "$out2"' 0 1 2 3 13 15

dms-dump $d1 $opts > $out1
dms-dump $d2 $opts > $out2

$DMSDIFF $out1 $out2

