Import('env')

env=env.Clone()
env.Prepend(CPPPATH=['../src'], LIBS=['msys', 'boost_filesystem', 'boost_system'])

env.AddProgram('mae2dms', 'converters/mae2dms.cxx')
env.AddProgram('dms2mae', 'converters/dms2mae.cxx')


## solvate
env.AddPythonModule('solvate/solvate.py', prefix='msys')
env.AddScript('solvate/dms-solvate')
env.AddShare('solvate/h2o.dms')

## neutralize
env.AddPythonModule('neutralize/neutralize.py', prefix='msys')
env.AddScript('neutralize/dms-neutralize')

# scripts
env.AddScript('scripts/dms-select')
