Import('msysenv')
Import('libmsys')

env=msysenv.Clone()
env.Prepend(CPPPATH=['../src'], LIBS=['msys', 'msys-core'])

# converters
env.AddProgram('mae2dms', 'converters/mae2dms.cxx')
env.AddProgram('dms2mae', 'converters/dms2mae.cxx')
env.AddProgram('msys-fetch-pdb', 'converters/msys-fetch-pdb.cxx')

## grease
env.AddPythonModule('grease/grease.py', prefix='msys')
env.AddScript('grease/dms-grease')

## posre
env.AddPythonModule('posre/posre.py', prefix='msys')
env.AddScript('posre/dms-posre')

# thermalize
env.AddPythonModule('thermalize/thermalize.py', prefix='msys')
env.AddScript('thermalize/dms-thermalize')

# validate
env.AddPythonModule('validate/validate.py', prefix='msys')
env.AddPythonModule('validate/knot.py', prefix='msys')
env.AddPythonModule('validate/groups.py', prefix='msys')
env.AddScript('validate/dms-validate')
env.AddScript('validate/dms-find-knot')
env.AddScript('validate/dtr-validate')

# info
env.AddProgram('dms-version', ['info/dms-version.cxx'])
env.AddScript('info/dms-diff')
env.AddScript('info/dms-dump')
env.AddScript('info/dms-info')
env.AddScript('info/dms-sequence')
env.AddPythonModule('info/sequence.py', prefix='msys')

# vdw
env.AddPythonModule('vdw/vdw.py', prefix='msys')
env.AddScript('vdw/dms-override-vdw')
env.AddScript('vdw/dms-scale-vdw')

# other scripts
env.AddScript('scripts/dms-check-groups')
env.AddScript('scripts/dms-fix-mass')
env.AddScript('scripts/dms-fix-water-residues')
env.AddScript('scripts/dms-frame')
env.AddScript('scripts/dms-reorder-atoms')
env.AddScript('scripts/dms-select')
env.AddScript('scripts/dms-set')
env.AddScript('scripts/dms-tile')
env.AddScript('scripts/dms-replicate')
env.AddPythonModule('scripts/update.py', prefix='msys')
env.AddPythonModule('scripts/wrap.py', prefix='msys')
env.AddPythonModule('scripts/reorder.py', prefix='msys')

