Import('msysenv')
Import('libmsys')
import sys
env=msysenv.Clone()

cxx_flags = '' if sys.platform.startswith("win32") else '-Wno-unused-local-typedefs'

env.Append( 
        CPPPATH=['../../src', '../'],
        CXXFLAGS=cxx_flags,
        LIBS=['msys', 'boost_python$MSYS_BOOST_SUFFIX'])

if sys.platform != "win32":
    env.Append(CCFLAGS='-Wno-unused-function'.split())
else:
    env.Append(LIBS=['python27.lib'])
if env['PLATFORM']=='darwin':
    env.Append(CCFLAGS='-Wno-error')
elif sys.platform.startswith("linux"):
    env.Append(CCFLAGS='-Wno-cpp')

srcs = Split('''
plugin.cxx
reader.cxx
atom.cxx
frame.cxx
writer.cxx
molfilemodule.cxx
''')

ext=env.AddPythonExtension('_molfile', srcs, prefix='msys/molfile')
env.Requires(ext, libmsys)

ext=env.AddPythonExtension('findframe','findframemodule.cxx',
        prefix='msys/molfile')
env.Requires(ext, libmsys)

env.AddPythonModule('__init__.py',prefix='msys/molfile')

# python3
env3 = msysenv.Clone()
env3.Append( 
        CPPPATH=['../../src', '../'],
        CXXFLAGS=cxx_flags,
        LIBS=['msys', 'boost_python3'])

if sys.platform != "win32":
    env3.Append(CCFLAGS='-Wno-unused-function'.split())
else:
    env3.Append(LIBS=['python27.lib'])
if env3['PLATFORM']=='darwin':
    env3.Append(CCFLAGS='-Wno-error')
elif sys.platform.startswith("linux"):
    env3.Append(CCFLAGS='-Wno-cpp')

ext=env3.AddPython3Extension('_molfile', srcs, prefix='msys/molfile')
env3.Requires(ext, libmsys)
env3.AddPython3Module('__init__.py',prefix='msys/molfile')

ext=env3.AddPython3Extension('findframe','findframemodule.cxx',
        prefix='msys/molfile')
env.Requires(ext, libmsys)
