#define OF                              1
#define AS                              2
#define TO                              3
#define OR                              4
#define AND                             5
#define ADD                             6
#define SUB                             7
#define MUL                             8
#define DIV                             9
#define MOD                            10
#define EXP                            11
#define NEG                            12
#define NOT                            13
#define VAL                            14
#define KEY                            15
#define LPAREN                         16
#define RPAREN                         17
#define MACRO                          18
#define WITHIN                         19
#define EXWITHIN                       20
#define PBWITHIN                       21
#define NEAREST                        22
#define INT                            23
#define WITHINBONDS                    24
#define PBNEAREST                      25
#define SAME                           26
#define CMP                            27
#define REGEX                          28
#define FLT                            29
#define PLUS                           30
#define FUNC                           31
