/** \file
 *  This C header file was generated by $ANTLR version 3.1.3 Mar 18, 2009 10:09:25
 *
 *     -  From the grammar source file : Vmd.g
 *     -                            On : 2011-11-09 16:48:04
 *     -                 for the lexer : VmdLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer VmdLexer has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 * 
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pVmdLexer, which is returned from a call to VmdLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 * * The methods in pVmdLexer are  as follows:
 *
 *  -  void      pVmdLexer->AND(pVmdLexer)
 *  -  void      pVmdLexer->OR(pVmdLexer)
 *  -  void      pVmdLexer->LESS(pVmdLexer)
 *  -  void      pVmdLexer->LESSEQ(pVmdLexer)
 *  -  void      pVmdLexer->MORE(pVmdLexer)
 *  -  void      pVmdLexer->MOREEQ(pVmdLexer)
 *  -  void      pVmdLexer->EQUAL(pVmdLexer)
 *  -  void      pVmdLexer->NEQUAL(pVmdLexer)
 *  -  void      pVmdLexer->WITHIN(pVmdLexer)
 *  -  void      pVmdLexer->WITHINBONDS(pVmdLexer)
 *  -  void      pVmdLexer->EXWITHIN(pVmdLexer)
 *  -  void      pVmdLexer->PBWITHIN(pVmdLexer)
 *  -  void      pVmdLexer->OF(pVmdLexer)
 *  -  void      pVmdLexer->SAME(pVmdLexer)
 *  -  void      pVmdLexer->AS(pVmdLexer)
 *  -  void      pVmdLexer->NOT(pVmdLexer)
 *  -  void      pVmdLexer->TO(pVmdLexer)
 *  -  void      pVmdLexer->T__33(pVmdLexer)
 *  -  void      pVmdLexer->T__34(pVmdLexer)
 *  -  void      pVmdLexer->T__35(pVmdLexer)
 *  -  void      pVmdLexer->T__36(pVmdLexer)
 *  -  void      pVmdLexer->T__37(pVmdLexer)
 *  -  void      pVmdLexer->T__38(pVmdLexer)
 *  -  void      pVmdLexer->T__39(pVmdLexer)
 *  -  void      pVmdLexer->T__40(pVmdLexer)
 *  -  void      pVmdLexer->T__41(pVmdLexer)
 *  -  void      pVmdLexer->LIT(pVmdLexer)
 *  -  void      pVmdLexer->REGEXVAL(pVmdLexer)
 *  -  void      pVmdLexer->ALPHA(pVmdLexer)
 *  -  void      pVmdLexer->DIGIT(pVmdLexer)
 *  -  void      pVmdLexer->WS(pVmdLexer)
 *  -  void      pVmdLexer->Tokens(pVmdLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_VmdLexer_H
#define _VmdLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */
 
#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct VmdLexer_Ctx_struct VmdLexer, * pVmdLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule 
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for VmdLexer
 */
struct VmdLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;


     void (*mAND)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mOR)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mLESS)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mLESSEQ)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mMORE)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mMOREEQ)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mEQUAL)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mNEQUAL)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mWITHIN)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mWITHINBONDS)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mEXWITHIN)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mPBWITHIN)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mOF)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mSAME)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mAS)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mNOT)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mTO)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mT__33)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mT__34)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mT__35)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mT__36)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mT__37)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mT__38)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mT__39)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mT__40)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mT__41)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mLIT)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mREGEXVAL)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mALPHA)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mDIGIT)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mWS)	(struct VmdLexer_Ctx_struct * ctx);
     void (*mTokens)	(struct VmdLexer_Ctx_struct * ctx);    const char * (*getGrammarFileName)();
    void	    (*free)   (struct VmdLexer_Ctx_struct * ctx);
        
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pVmdLexer VmdLexerNew         (pANTLR3_INPUT_STREAM instream);
ANTLR3_API pVmdLexer VmdLexerNewSSD      (pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the lexer will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif 
#define FUNCTION      13
#define WITHINBONDS      20
#define UNARYOP      15
#define NEQUAL      11
#define T__40      40
#define REGEXVAL      29
#define T__41      41
#define KEYWORD      12
#define TO      27
#define LIT      28
#define RELATION      14
#define REGEX      18
#define LITERAL      17
#define NOT      26
#define AND      4
#define EOF      -1
#define OF      23
#define SAME      24
#define ALPHA      30
#define AS      25
#define MOREEQ      9
#define T__33      33
#define WS      32
#define T__34      34
#define T__35      35
#define MORE      8
#define LESSEQ      7
#define T__36      36
#define PBWITHIN      22
#define T__37      37
#define T__38      38
#define BINARYOP      16
#define T__39      39
#define EQUAL      10
#define OR      5
#define LESS      6
#define EXWITHIN      21
#define WITHIN      19
#define DIGIT      31
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for VmdLexer
 * =============================================================================
 */
/** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
